#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 数据库检测.MODEL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SUDA")]
	public partial class ShuJuKuDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insert__MigrationHistory(__MigrationHistory instance);
    partial void Update__MigrationHistory(__MigrationHistory instance);
    partial void Delete__MigrationHistory(__MigrationHistory instance);
    partial void InsertZuzhipeixing_linchuanghla_jianceshenqingdan(Zuzhipeixing_linchuanghla_jianceshenqingdan instance);
    partial void UpdateZuzhipeixing_linchuanghla_jianceshenqingdan(Zuzhipeixing_linchuanghla_jianceshenqingdan instance);
    partial void DeleteZuzhipeixing_linchuanghla_jianceshenqingdan(Zuzhipeixing_linchuanghla_jianceshenqingdan instance);
    partial void InsertYonghu(Yonghu instance);
    partial void UpdateYonghu(Yonghu instance);
    partial void DeleteYonghu(Yonghu instance);
    #endregion
		
		public ShuJuKuDataContext() : 
				base(global::数据库检测.Properties.Settings.Default.sudaitswellConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ShuJuKuDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShuJuKuDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShuJuKuDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ShuJuKuDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<@__MigrationHistory> @__MigrationHistory
		{
			get
			{
				return this.GetTable<@__MigrationHistory>();
			}
		}
		
		public System.Data.Linq.Table<Zuzhipeixing_linchuanghla_jianceshenqingdan> Zuzhipeixing_linchuanghla_jianceshenqingdan
		{
			get
			{
				return this.GetTable<Zuzhipeixing_linchuanghla_jianceshenqingdan>();
			}
		}
		
		public System.Data.Linq.Table<Yonghu> Yonghu
		{
			get
			{
				return this.GetTable<Yonghu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[__MigrationHistory]")]
	public partial class @__MigrationHistory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MigrationId;
		
		private string _ContextKey;
		
		private System.Data.Linq.Binary _Model;
		
		private string _ProductVersion;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMigrationIdChanging(string value);
    partial void OnMigrationIdChanged();
    partial void OnContextKeyChanging(string value);
    partial void OnContextKeyChanged();
    partial void OnModelChanging(System.Data.Linq.Binary value);
    partial void OnModelChanged();
    partial void OnProductVersionChanging(string value);
    partial void OnProductVersionChanged();
    #endregion
		
		public @__MigrationHistory()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MigrationId", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MigrationId
		{
			get
			{
				return this._MigrationId;
			}
			set
			{
				if ((this._MigrationId != value))
				{
					this.OnMigrationIdChanging(value);
					this.SendPropertyChanging();
					this._MigrationId = value;
					this.SendPropertyChanged("MigrationId");
					this.OnMigrationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContextKey", DbType="NVarChar(300) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ContextKey
		{
			get
			{
				return this._ContextKey;
			}
			set
			{
				if ((this._ContextKey != value))
				{
					this.OnContextKeyChanging(value);
					this.SendPropertyChanging();
					this._ContextKey = value;
					this.SendPropertyChanged("ContextKey");
					this.OnContextKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Model", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Model
		{
			get
			{
				return this._Model;
			}
			set
			{
				if ((this._Model != value))
				{
					this.OnModelChanging(value);
					this.SendPropertyChanging();
					this._Model = value;
					this.SendPropertyChanged("Model");
					this.OnModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductVersion", DbType="NVarChar(32) NOT NULL", CanBeNull=false)]
		public string ProductVersion
		{
			get
			{
				return this._ProductVersion;
			}
			set
			{
				if ((this._ProductVersion != value))
				{
					this.OnProductVersionChanging(value);
					this.SendPropertyChanging();
					this._ProductVersion = value;
					this.SendPropertyChanged("ProductVersion");
					this.OnProductVersionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Zuzhipeixing_linchuanghla_jianceshenqingdan")]
	public partial class Zuzhipeixing_linchuanghla_jianceshenqingdan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _huanzhexingming;
		
		private string _xingbie;
		
		private System.Nullable<System.DateTime> _chushengriqi;
		
		private bool _zhiqingtongyi;
		
		private string _shenqingyiyuan;
		
		private string _shenqingdanbianhao;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnhuanzhexingmingChanging(string value);
    partial void OnhuanzhexingmingChanged();
    partial void OnxingbieChanging(string value);
    partial void OnxingbieChanged();
    partial void OnchushengriqiChanging(System.Nullable<System.DateTime> value);
    partial void OnchushengriqiChanged();
    partial void OnzhiqingtongyiChanging(bool value);
    partial void OnzhiqingtongyiChanged();
    partial void OnshenqingyiyuanChanging(string value);
    partial void OnshenqingyiyuanChanged();
    partial void OnshenqingdanbianhaoChanging(string value);
    partial void OnshenqingdanbianhaoChanged();
    #endregion
		
		public Zuzhipeixing_linchuanghla_jianceshenqingdan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_huanzhexingming", DbType="NVarChar(MAX)")]
		public string huanzhexingming
		{
			get
			{
				return this._huanzhexingming;
			}
			set
			{
				if ((this._huanzhexingming != value))
				{
					this.OnhuanzhexingmingChanging(value);
					this.SendPropertyChanging();
					this._huanzhexingming = value;
					this.SendPropertyChanged("huanzhexingming");
					this.OnhuanzhexingmingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xingbie", DbType="NVarChar(MAX)")]
		public string xingbie
		{
			get
			{
				return this._xingbie;
			}
			set
			{
				if ((this._xingbie != value))
				{
					this.OnxingbieChanging(value);
					this.SendPropertyChanging();
					this._xingbie = value;
					this.SendPropertyChanged("xingbie");
					this.OnxingbieChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chushengriqi", DbType="DateTime")]
		public System.Nullable<System.DateTime> chushengriqi
		{
			get
			{
				return this._chushengriqi;
			}
			set
			{
				if ((this._chushengriqi != value))
				{
					this.OnchushengriqiChanging(value);
					this.SendPropertyChanging();
					this._chushengriqi = value;
					this.SendPropertyChanged("chushengriqi");
					this.OnchushengriqiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zhiqingtongyi", DbType="Bit NOT NULL")]
		public bool zhiqingtongyi
		{
			get
			{
				return this._zhiqingtongyi;
			}
			set
			{
				if ((this._zhiqingtongyi != value))
				{
					this.OnzhiqingtongyiChanging(value);
					this.SendPropertyChanging();
					this._zhiqingtongyi = value;
					this.SendPropertyChanged("zhiqingtongyi");
					this.OnzhiqingtongyiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shenqingyiyuan", DbType="NVarChar(MAX)")]
		public string shenqingyiyuan
		{
			get
			{
				return this._shenqingyiyuan;
			}
			set
			{
				if ((this._shenqingyiyuan != value))
				{
					this.OnshenqingyiyuanChanging(value);
					this.SendPropertyChanging();
					this._shenqingyiyuan = value;
					this.SendPropertyChanged("shenqingyiyuan");
					this.OnshenqingyiyuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shenqingdanbianhao", DbType="NVarChar(MAX)")]
		public string shenqingdanbianhao
		{
			get
			{
				return this._shenqingdanbianhao;
			}
			set
			{
				if ((this._shenqingdanbianhao != value))
				{
					this.OnshenqingdanbianhaoChanging(value);
					this.SendPropertyChanging();
					this._shenqingdanbianhao = value;
					this.SendPropertyChanged("shenqingdanbianhao");
					this.OnshenqingdanbianhaoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Yonghu")]
	public partial class Yonghu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _zhanghao;
		
		private string _mima;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnzhanghaoChanging(string value);
    partial void OnzhanghaoChanged();
    partial void OnmimaChanging(string value);
    partial void OnmimaChanged();
    #endregion
		
		public Yonghu()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zhanghao", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string zhanghao
		{
			get
			{
				return this._zhanghao;
			}
			set
			{
				if ((this._zhanghao != value))
				{
					this.OnzhanghaoChanging(value);
					this.SendPropertyChanging();
					this._zhanghao = value;
					this.SendPropertyChanged("zhanghao");
					this.OnzhanghaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mima", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string mima
		{
			get
			{
				return this._mima;
			}
			set
			{
				if ((this._mima != value))
				{
					this.OnmimaChanging(value);
					this.SendPropertyChanging();
					this._mima = value;
					this.SendPropertyChanged("mima");
					this.OnmimaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
